version: "3"

services:

  melon-bot:
    build: ../melon-bot/
    container_name: melon-bot
    restart: always
    env_file:
      - ./melon_bot_variables.env
    networks:
      - main-net

  bot-base-mongo:
    image: mongo
    restart: always
    environment:
      - ./mongo_bot_variables.env

  bot-base-mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ./mongo_express_bot_variables.env
      
networks:
  main-net:
    external: true

