version: "3"

services:

  melon-bot:
    build: ../melon-bot/
    container_name: melon-bot
    restart: always
    env_file:
      - ./melon_bot_variables.env
    networks:
      - main-net

  bb-mongo:
    image: mongo:latest
    container_name: bb-mongo
    restart: always
    environment:
      - ./mongo_bot_variables.env
    volumes:
      - /var/data/bot-base/mongo/data:/data/db
    networks:
      - main-net
    
  bb-mongo-express:
    image: mongo-express
    container_name: bb-mongo-express
    restart: always
    env_file:
      - ./mongo_express_bot_variables.env
    networks:
      - main-net
    depends_on:
      - bb-mongo
      
networks:
  main-net:
    external: true

