version: "3"

services:

  melon-bot:
    build: ../melon-bot/
    container_name: melon-bot
    restart: always
    env_file:
      - ./melon_bot_variables.env
    networks:
      - main-net

  bb-mongo:
    image: mongo:latest
    container_name: bb-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_INITDB_DATABASE: admins

  bb-mongo-express:
    image: mongo-express
    container_name: bb-mongo-express
    restart: always
    env_file:
      - ./mongo_express_bot_variables.env
    networks:
      - main-net
      
networks:
  main-net:
    external: true

