version: "3"

services:

  melon-bot:
    build: ../melon-bot/
    container_name: melon-bot
    restart: always
    env_file:
      - ./melon_bot_variables.env
    networks:
      - main-net

  bot-base-mongo:
    image: mongo
    container_name: bot-base-mongo
    restart: always
    env_file:
      - ./mongo_bot_variables.env
    volumes: 
      - /var/data/bot-base/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_ROOT_DATABASE}

  bot-base-mongo-express:
    image: mongo-express
    container_name: bot-base-mongo-express
    restart: always
    env_file:
      - ./mongo_express_bot_variables.env
      
networks:
  main-net:
    external: true

